apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhttpd-dev
spec:
  selector:
    matchLabels:
      run: myhttpd-dev
  replicas: 2
  template:
    metadata:
      labels:
        run: myhttpd-dev
    spec:
      containers:
      - name: my-httpd
        image: mstelles/myhttpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs/
          name: www
      volumes:
      - name: www
        hostPath:
          path: /var/www/
---
apiVersion: v1
kind: Service
metadata:
  name: myhttpd-dev
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true
  labels:
    run: myhttpd-dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: myhttpd-dev
